ngcode: en
status: true
dependencies: {  }
id: client_active
label: 'Client Active'
description: 'Client Active config'
folder: /opt/www/d8_configs/default/splits/client/active
module: {  }
theme: {  }
blacklist: {  }
graylist:
    - '*'
graylist_dependents: true
graylist_skip_equal: true
weight: 5
